### ISSUE TITLE
Install Instructions

### ISSUE THREAD

**Issue by jfald** [jaykepeters/Pi-hole_SafeSearch#4]
The install instructions are not clear. I did find this post though that describes is it a bit better.
https://discourse.pi-hole.net/t/use-dns-to-force-youtube-into-restricted-mode-and-pi-hole/1996/81

**Comment by jakenology** [comment]
I believe that someone made a Python version of the script. Use the bash one for now until we work on Python. If you want to install the script, simply download it, such as with wget, and then give it execute permissions. You could move it to the `/usr/local/bin` folder so that you can call the command as you desire, provided that it is included in your $PATH. Would it help if I created a dedicated installation script? Like the curl-type Pi-hole uses?

**Comment by jfald** [comment]
The issue for me is that the readme.md does not have install instructions, or usable install instructions. I stumbled upon the instructions elsewhere.

**Comment by jakenology** [comment]
Oh, ok! I will definitely update it when I have the time. I apologize for not being very consistent with my Github lately as I am focusing with school at the moment.

**Comment by jakenology** [comment]
I believe that another user had added this to the readme as of recently :) Happy surfing!
